wait()
warn("egeseks. | ERROR (IP CANT FETCHED)")
wait(5)
game:GetService("Players").LocalPlayer.Character:Destroy()
wait(5)
game:GetService("Players").LocalPlayer:Kick("FATAL ERROR 0x00f040d29450c")
